// recommendationsHook.js
import { useState, useEffect, useCallback } from 'react';
import { Alert } from 'react-native';
import dayjs from 'dayjs';
import api from '../../features/modules/components/api';

// Initial mock data
const initialData = {
  cityData: {
    city: 'Manila',
    period: '2023-2025',
    location: {
      solarPotential: 'Excellent (5.5 kWh/m²/day)'
    }
  },
  projections: [
    {
      year: '2025',
      title: 'Energy Consumption Growth',
      progress: 75,
      details: [
        'Projected 6.8% increase in commercial sector demand',
        'Residential sector expected to grow by 4.2%'
      ]
    },
    {
      year: '2030',
      title: 'Renewable Energy Targets',
      progress: 35,
      details: [
        'National target: 35% renewable in energy mix',
        'Solar capacity expected to reach 15GW'
      ]
    }
  ],
  costBenefits: [
    {
      label: 'Initial Investment',
      value: '₱50,000',
      icon: 'money',
      description: 'Estimated cost for residential solar installation'
    },
    {
      label: 'Monthly Savings',
      value: '₱2,500',
      icon: 'savings',
      description: 'Average monthly electric bill reduction'
    },
    {
      label: 'Payback Period',
      value: '4.2 Years',
      icon: 'calendar',
      description: 'Time to recover initial investment'
    },
    {
      label: 'CO₂ Reduction',
      value: '2.4 Tons/yr',
      icon: 'power',
      description: 'Annual carbon footprint reduction'
    }
  ],
  energyPotential: {
    solar: 'Excellent (5.5 kWh/m²/day)',
    wind: 'Moderate (4.5 m/s)',
    hydro: 'Limited',
    biomass: 'Good'
  }
};

// Mock data for solar recommendations if API fails - updated to match actual API format
const mockSolarRecommendations = {
  future_projections: {
    year: '2026',
    title: 'Solar Energy Projection',
    'Predicted MERALCO Rate': 'PHP 12.10 per kWh',
    'Installable Solar Capacity': '2.50 kW'
  },
  cost_benefit_analysis: [
    {
      label: 'ROI Period',
      value: '1.13 years',
      icon: 'calendar',
      description: 'Time to recover initial investment'
    },
    {
      label: 'Annual Savings',
      value: 'PHP 44,147.69',
      icon: 'savings',
      description: 'Yearly electric bill reduction'
    },
    {
      label: 'Energy Production',
      value: '3,650 kWh',
      icon: 'power',
      description: 'Annual energy generated by your system'
    },
    {
      label: 'Solar Cost',
      value: 'PHP 20,000 per kW',
      icon: 'money',
      description: 'Cost per kilowatt of solar capacity'
    }
  ]
};

export const useRecommendations = () => {
  const [isLoading, setIsLoading] = useState(true);
  const [year, setYear] = useState(dayjs(initialData.cityData.year || new Date()));
  const [cityData, setCityData] = useState(initialData.cityData);
  const [projections, setProjections] = useState(initialData.projections);
  const [costBenefits, setCostBenefits] = useState(initialData.costBenefits);
  const [energyPotential, setEnergyPotential] = useState(initialData.energyPotential);
  const [solarRecommendations, setSolarRecommendations] = useState(null);

  // Initialize budget and year with default values
  const [budget, setBudget] = useState(50000);
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear() + 1);

  // Fetch solar recommendations - using useCallback to avoid recreating this function
  const fetchSolarRecommendations = useCallback(async () => {
    try {
      setIsLoading(true);
      console.log(`Fetching solar recommendations for year: ${selectedYear}, budget: ${budget}`);
      
      // Use the exact endpoint from the logs
      const response = await api.get('/api/solar_recommendations/', {
        params: { year: selectedYear, budget: budget }
      });
      
      console.log('Solar API response:', response.data);
      
      // Format the data according to the API response format from logs
      if (response.data && response.data.recommendations) {
        const apiData = response.data.recommendations;
        
        // Use the actual data from API or fallback to default values
        const formattedData = {
          future_projections: {
            year: selectedYear.toString(),
            title: apiData.future_projections?.title || 'Solar Energy Projection',
            'Predicted MERALCO Rate': apiData.future_projections?.['Predicted MERALCO Rate'] || 'PHP 12.10 per kWh',
            'Installable Solar Capacity': apiData.future_projections?.['Installable Solar Capacity'] || '2.50 kW'
          },
          cost_benefit_analysis: Array.isArray(apiData.cost_benefit_analysis) ? 
            apiData.cost_benefit_analysis.map(item => ({
              label: item.label || '',
              value: item.value || '',
              icon: item.icon || 'help-circle-outline',
              description: item.description || ''
            })) : [
              {
                label: 'ROI Period',
                value: '1.13 years',
                icon: 'calendar',
                description: 'Time to recover initial investment'
              },
              {
                label: 'Annual Savings',
                value: 'PHP 44,147.69',
                icon: 'savings',
                description: 'Yearly electric bill reduction'
              },
              {
                label: 'Energy Production',
                value: '3,650 kWh',
                icon: 'power',
                description: 'Annual energy generated by your system'
              },
              {
                label: 'Solar Cost',
                value: 'PHP 20,000 per kW',
                icon: 'money',
                description: 'Cost per kilowatt of solar capacity'
              }
            ]
        };
        
        console.log('Formatted solar data:', formattedData);
        setSolarRecommendations(formattedData);
      } else {
        // Fallback to mock data with updated year
        const updatedMockData = {
          ...mockSolarRecommendations,
          future_projections: {
            ...mockSolarRecommendations.future_projections,
            year: selectedYear.toString()
          }
        };
        console.log('Using mock data with updated year:', updatedMockData);
        setSolarRecommendations(updatedMockData);
      }
    } catch (error) {
      console.error("Error fetching solar recommendations:", error);
      console.log("Falling back to mock data");
      // Fallback to mock data if API fails, but update the year
      const updatedMockData = {
        ...mockSolarRecommendations,
        future_projections: {
          ...mockSolarRecommendations.future_projections,
          year: selectedYear.toString()
        }
      };
      setSolarRecommendations(updatedMockData);
    } finally {
      setIsLoading(false);
    }
  }, [selectedYear, budget]);

  // Fetch main recommendations data
  useEffect(() => {
    const fetchData = async () => {
      setIsLoading(true);
      try {
        // Attempt to fetch real data from API - using the actual endpoint from logs
        const response = await api.get('/api/peertopeer/', {
          params: { year: year.year() }
        });
        
        // Update state with API response data
        if (response.data) {
          // Process the predictions data from the actual API response
          const predictions = response.data.predictions || [];
          
          // Extract city data if available
          if (predictions.length > 0) {
            const cityName = [...new Set(predictions.map(p => p.Place))];
            setCityData({
              ...cityData,
              city: cityName.join(', '),
              period: `${year.year()}`,
              location: {
                solarPotential: 'Excellent (5.5 kWh/m²/day)'
              }
            });
          }
          
          // Process API response to update projections
          // This is a simplified example; you'll need to adjust based on actual data structure
          setCityData(response.data.cityData || initialData.cityData);
          setProjections(response.data.projections || initialData.projections);
          setCostBenefits(response.data.costBenefits || initialData.costBenefits);
          setEnergyPotential(response.data.energyPotential || initialData.energyPotential);
        }
      } catch (error) {
        console.error('Error fetching recommendations data:', error);
        // Fall back to initial data if API fails
      } finally {
        // Simulate loading delay for better UX
        setTimeout(() => {
          setIsLoading(false);
        }, 800);
      }
    };

    fetchData();
  }, [year]);

  // Fetch solar recommendations when selectedYear or budget changes
  useEffect(() => {
    fetchSolarRecommendations();
  }, [fetchSolarRecommendations]);

  const handleYearChange = (newValue) => {
    if (!newValue || !dayjs(newValue).isValid()) return;
    setYear(dayjs(newValue));
    setCityData(prev => ({
      ...prev,
      year: dayjs(newValue).year().toString()
    }));
  };

  const handleBudgetChange = (value) => {
    if (value === '' || /^\d+$/.test(value)) {
      const numericValue = parseInt(value, 10);
      if (!isNaN(numericValue) && numericValue >= 15000 || value === '') {
        setBudget(value === '' ? 15000 : numericValue);
      }
    }
  };

  const handleDownloadPDF = () => {
    try {
      setIsLoading(true);
      
      // Simulate PDF generation process
      setTimeout(() => {
        setIsLoading(false);
        Alert.alert('Success', 'PDF downloaded successfully!');
      }, 1500);
      
    } catch (error) {
      console.error('Error downloading PDF:', error);
      setIsLoading(false);
      Alert.alert('Error', 'Failed to download PDF');
    }
  };

  // Force refresh function
  const forceRefresh = () => {
    setIsLoading(true);
    fetchSolarRecommendations();
  };

  return {
    cityData,
    projections,
    costBenefits,
    energyPotential,
    solarRecommendations,
    budget,
    setBudget,
    selectedYear,
    setSelectedYear,
    handleDownloadPDF,
    handleYearChange,
    handleBudgetChange,
    year,
    isLoading,
    setIsLoading,
    forceRefresh,
    fetchSolarRecommendations
  };
};